services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    UMLGenerationBundle\Command\UMLGenerationCommand:
        arguments:
            $classDefinitionsRepository: '@UMLGenerationBundle\Repository\ClassDefinitionsRepositoryInterface'
        tags: [ 'console.command' ]

    UMLGenerationBundle\Repository\ClassDefinitionsRepositoryInterface:
        class: UMLGenerationBundle\Repository\ClassDefinitionsRepository

    UMLGenerationBundle\Formatter\RelationsFormatter: ~

    UMLGenerationBundle\Formatter\AttributeFormatter: ~

    UMLGenerationBundle\Formatter\ClassFormatter:
        arguments:
            $attributeFormatter: '@UMLGenerationBundle\Formatter\AttributeFormatter'

    UMLGenerationBundle\Service\PrinterService: ~

    UMLGenerationBundle\Service\ClassDefinition2UMLService:
        arguments:
            $fieldDefinitionHandlers:
                - '@UMLGenerationBundle\Handler\FieldDefinition\ManyToOneRelationHandler'
                - '@UMLGenerationBundle\Handler\FieldDefinition\ManyToManyRelationHandler'
                - '@UMLGenerationBundle\Handler\FieldDefinition\ReverseObjectRelationHandler'